### ISSUE TITLE
Wrong link in the README.md

### ISSUE THREAD

**Issue by Unaimend** [JetBrains-Research/bioinf-commons#13]
Hi, just wanted to let you know that there is a small error in your READE
![image](https://user-images.githubusercontent.com/7808379/195932416-ae68c406-5252-4f60-9ff8-55c2d9976e2f.png)

The JBR link is linking to the span project instead of https://github.com/JetBrains-Research/jbr.

Have a nice day :)

**Comment by olegs** [comment]
Thank's a lot for pointing this out, we have already fixed this. Closing the issue.
Have a nice day :)
