### ISSUE TITLE
Adding CpG track shows empty track for hs1 genome reference

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/bioinf-commons#17]

**Comment by serge-p7v** [comment]
I haven't added CpG track for hs1 yet, but it seems it can be done. It's in BigBed format and available by one of these links
https://hgdownload.soe.ucsc.edu/gbdb/hs1/bbi/cpgIslandExt.bb
https://hgdownload.soe.ucsc.edu/gbdb/hs1/bbi/cpgIslandExtUnmasked.bb
