### ISSUE TITLE
Bed format detection problems

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/bioinf-commons#2]
A file consisting of exactly one line will always be recognized as a valid BED file by `BedFormat.auto` due to the algorithm that skips one malformed line on account that it might be a header. The same is true for any file that has exactly one line that doesn't match `NON_DATA_LINE_PATTERN`. This is probably not the intended behaviour.
Example: `chr1\t2` is recognized as a valid `bed3` file.

**Comment by dievsky** [comment]
Various other BED format detection problems:
- when `score` column is integer in the first line, but can be double later on;
- when `score` column is in `Short` range in the first line, but exceeds 2^15 later on, see e.g. JetBrains-Research/jbr#65.

**Comment by olegs** [comment]
Actually even MACS2 in its documentation claims the following: "Please note that currently this value (score) might be out of the [0-1000] range defined in UCSC Encode narrowPeak format"
See https://github.com/taoliu/MACS

**Comment by dievsky** [comment]
Yep, though MACS2's score is usually still in the short range.
We might be better off by changing the score field to double.

**Comment by olegs** [comment]
Another option: we might read it as double and trim to 1000 following ENCODE BroadPeak standrard.

**Comment by dievsky** [comment]
The standard doesn't seem to provide any specific conversion for the case when score is not integer in [0,1000], nor does it even acknowledge such a case. And if SICER or MACS2 choose to report the score as 56000, I don't see a justification of trimming it to 1000.
By the way, the visual trimming can be achieved at any time by setting the Scale Max to 1000 in the browser. It will make any value higher than 1000 exactly the same colour as 1000.
Thus I suggest just always reading the score field as double, or at least as float (to save RAM when loading large BED files).

**Comment by dievsky** [comment]
Amendment: though many BED providers don't respect 0-1000 limits, they do seem to always generate an integer score. Thus I suggest defining and reading score as integer. This will require an appropriate edit to `big`.

**Comment by iromeo** [comment]
@olegs @dievsky Are we aware of any BED-like file where `score` is out of [0,1000] range, but the file isn't in `BED4+K` format? E.g. MACS2 narrow peaks are `BED4+6`, SICER is `BED4+`. I'm not against changing `score` to Int/Double/String/WhatEver, but do we really have a reason for it?

**Comment by dievsky** [comment]
As previously mentioned (and stated in the README), MACS2 is formally `bed6+4` (or `bed6+3` for broad peaks).

**Comment by iromeo** [comment]
@dievsky Ok, seems I have use case we the suggested fix is desired. In #67 or #65 we cannot determine that score column doesn't match the specification from first lines because they are < 1000 and the wrong value is somewhere later in the file.

**Comment by dievsky** [comment]
@iromeo I'd say that's a separate problem, but in this particular case it can be solved by this approach.

**Comment by iromeo** [comment]
@dievsky we don't use MACS2 readme information because we detect format automatically from first lines. I think that `bed6+4` mentioning is a bug in MAC2 readme and could be fixed by MACS2 team.

**Comment by dievsky** [comment]
I'm afraid that between us and MACS2, people would tend to listen to their definition of `bed6+4` format, not ours. Yes, "ours" is backed by UCSC, but the usage usually beats a codified standard.

**Comment by olegs** [comment]
Agree with @dievsky here. Users don't care about formats, the want things to just work.

**Comment by iromeo** [comment]
> A file consisting of exactly one line will always be recognized as a valid BED file by `BedFormat.auto`
Is it a real use case or a synthetic one? I don't think that we need to fix it somehow.

**Comment by dievsky** [comment]
A one-line BED is a synthetic case, but the format autodetection problems are systematic. Worse, they lead to UX failures, like when JBR refuses to open a file because it guessed the format wrong. and there's no sane way to circumvent this. In my opinion, if a file provides the first 3 obligatory BED fields, JBR should open it one way or another.

**Comment by dievsky** [comment]
In my opinion, a systematic solution would look like this:
- Drop the extra fields parameter from a BedFormat. We never use the actual number anyway. Replace it with a boolean argument to `pack/unpack/rest/etc` methods which would indicate whether we want to keep or drop the extra fields. Just implicitly (or explicitly) treat `bedN` as `bedN+K`.
- Introduce a total order on the set of possible Bed formats: `bedFormat1 >= bedFormat2` iff `bedFormat1` has at least as many regular fields as `bedFormat2`.
- For example, `bed3+K` is the minimum possible format, while `bed4+K < bed5+K`. The reasoning here is that a "lesser" format can consume anything that is readable by a "greater" format. `bed3+K` can consume any BED file; `bed4+K` can consume `bed5+K` entries, the 5th column will be treated as an extra field.
- Detect BED format simultaneously with parsing a BED file. For each line, determine a maximum format that accepts it, and update the resulting format as necessary.
- Skip any lines that can't be parsed at all (i.e. not even with `bed3+K`).

If we implement this, we'll stop having problems with wrong auto detection and we'll never fail to open and render a BED file.

**Comment by dievsky** [comment]
The latest pull request #3 will finally implement the last bullet point of the previous comment (skip any non-parseable lines).
